CREATE TABLE CATEGORIA
(
  IDCat INT NOT NULL,
  NomeCat VARCHAR(20) NOT NULL,
  IDCatPai INT NOT NULL,
  PRIMARY KEY (IDCat),
);


CREATE TABLE PRODUTO
(
  IDProd INT NOT NULL,
  NomeProd VARCHAR(20) NOT NULL,
  DescricaoProd VARCHAR(100) NULL, --VERIFICAR N EM VARCHAR(N)
  PrecoVendaProd MONEY NOT NULL,
  EstoqueAtualProd FLOAT NOT NULL,
  PrecoCustoProd MONEY NOT NULL,
  UnidadeProd FLOAT NOT NULL,
  IDCat INT NOT NULL,
  PRIMARY KEY (IDProd),
);

CREATE TABLE FORNECEDOR
(
  IDForn INT NOT NULL,
  NomeForn VARCHAR(50) NOT NULL,
  CNPJForn CHAR(14) NOT NULL, -- 18 com pontos e 14 sem
  PRIMARY KEY (IDForn)
);

CREATE TABLE CLIENTE
(
  IDCliente INT NOT NULL,
  NomeCliente VARCHAR(50) NOT NULL,
  DataNascCliente DATE NOT NULL,
  CPFCliente INT NOT NULL,
  PRIMARY KEY (IDCliente)
);

CREATE TABLE VENDEDOR
(
  IDVend INT NOT NULL,
  NomeVend VARCHAR(50) NOT NULL,
  CPFVend CHAR(11) NOT NULL, -- 14 com pontos, 11 sem 
  DataNascVend DATE NOT NULL,
  CelVend VARCHAR(12) NOT NULL,
  SalarioVend MONEY NOT NULL,
  PRIMARY KEY (IDVend)
);

CREATE TABLE CAIXA
(
  IDCaixa INT NOT NULL,
  TipoCaixa VARCHAR(20) NOT NULL,
  PRIMARY KEY (IDCaixa)
);

CREATE TABLE OPERACAOCAIXA
(
  IDOperacao INT NOT NULL,
  DataOpAber TIMESTAMP NOT NULL,
  ValorOpAber MONEY NOT NULL,
  DataOpFecham TIMESTAMP NOT NULL,
  ValorOpFecham MONEY NOT NULL,
  SaldoOp MONEY NOT NULL,
  IDVend INT NOT NULL,
  IDCaixa INT NOT NULL,
  PRIMARY KEY (IDOperacao),
);

CREATE TABLE PEDIDO
(
  IDPedido INT NOT NULL,
  ValorTotalPedido MONEY NOT NULL,
  DataPedido TIMESTAMP NOT NULL,
  TipoPedido VARCHAR(20) NOT NULL,
  IDCliente INT NOT NULL,
  IDOperacao INT NOT NULL,
  PRIMARY KEY (IDPedido),
);

CREATE TABLE PAGAMENTO
(
  IDPag INT NOT NULL,
  MetodoPag VARCHAR(10) NOT NULL,
  ValorPag MONEY NOT NULL,
  DataPag TIMESTAMP NOT NULL,
  IDPedido INT NOT NULL,
  PRIMARY KEY (IDPag),
);

CREATE TABLE ITEMPEDIDO
(
  IDProd INT NOT NULL,
  IDPedido INT NOT NULL,
  QtdItem FLOAT NOT NULL,
  DescItem MONEY,
  PrecoUn MONEY NOT NULL,
  PRIMARY KEY (IDProd, IDPedido),
);

CREATE TABLE PERDAESTOQUE
(
  IDPerda INT NOT NULL,
  DataPerda TIMESTAMP NOT NULL,
  QtdPerda FLOAT NOT NULL,
  MotivoPerda VARCHAR(100) NOT NULL,
  ValorUnPerda MONEY NOT NULL,
  IDProd INT NOT NULL,
  PRIMARY KEY (IDPerda),
);

CREATE TABLE ENTRADAESTOQUE
(
  IDForn INT NOT NULL,
  IDProd INT NOT NULL,
  EntradaData TIMESTAMP NOT NULL,
  EntradaQtd FLOAT NOT NULL,
  EntradaPreco MONEY NOT NULL,
  PRIMARY KEY (IDForn, IDProd),
);

CREATE TABLE ENDERECO
(
  EndereçoID INT NOT NULL,
  RuaEnd VARCHAR(35) NOT NULL,
  NumeroEnd INT NOT NULL,
  ComplemEnd VARCHAR(20),
  CEPEnd CHAR(10) NOT NULL, -- 10 COM PONTOS E 8 SEM PONTOS
  BairroEnd VARCHAR(20) NOT NULL,
  CidadeEnd VARCHAR(25) NOT NULL,
  EstadoEnd CHAR(2) NOT NULL,
  PaisEnd VARCHAR(20) NOT NULL,
  PRIMARY KEY (EndereçoID)
);

CREATE TABLE ENDERECOCLIENTE
(
  IDCliente INT NOT NULL,
  EndereçoID INT NOT NULL,
  PRIMARY KEY (EndereçoID),
);

CREATE TABLE ENDERECOVENDEDOR
(
  IDVend INT NOT NULL,
  EndereçoID INT NOT NULL,
  PRIMARY KEY (EndereçoID),
);

CREATE TABLE ENDERECOFORNEC
(
  IDForn INT NOT NULL,
  EndereçoID INT NOT NULL,
  PRIMARY KEY (EndereçoID),
  );

CREATE TABLE FORNECEDOR_CELFORN
(
  CelForn INT NOT NULL,
  IDForn INT NOT NULL,
  PRIMARY KEY (CelForn, IDForn),
);

CREATE TABLE CLIENTE_CELCLIENTE
(
  CelCliente INT NOT NULL,
  IDCliente INT NOT NULL,
  PRIMARY KEY (CelCliente, IDCliente),
);

ALTER TABLE CATEGORIA ADD FOREIGN KEY (IDCatPai) REFERENCES CATEGORIA(IDCat);

ALTER TABLE PRODUTO ADD FOREIGN KEY (IDCat) REFERENCES CATEGORIA(IDCat)

ALTER TABLE OPERACAOCAIXA ADD FOREIGN KEY (IDVend) REFERENCES VENDEDOR(IDVend),
ALTER TABLE OPERACAOCAIXA ADD FOREIGN KEY (IDCaixa) REFERENCES CAIXA(IDCaixa)

ALTER TABLE PEDIDO ADD FOREIGN KEY (IDCliente) REFERENCES CLIENTE(IDCliente),
ALTER TABLE PEDIDO ADD FOREIGN KEY (IDOperacao) REFERENCES OPERACAOCAIXA(IDOperacao)

ALTER TABLE PAGAMENTO ADD FOREIGN KEY (IDPedido) REFERENCES PEDIDO(IDPedido)

ALTER TABLE ITEMPEDIDO ADD FOREIGN KEY (IDProd) REFERENCES PRODUTO(IDProd),
ALTER TABLE ITEMPEDIDO ADD FOREIGN KEY (IDPedido) REFERENCES PEDIDO(IDPedido)

ALTER TABLE PERDAESTOQUE ADD FOREIGN KEY (IDProd) REFERENCES PRODUTO(IDProd)

ALTER TABLE ENTRADAESTOQUE ADD FOREIGN KEY (IDForn) REFERENCES FORNECEDOR(IDForn),
ALTER TABLE ENTRADAESTOQUE ADD FOREIGN KEY (IDProd) REFERENCES PRODUTO(IDProd)

ALTER TABLE ENDERECOCLIENTE ADD FOREIGN KEY (IDCliente) REFERENCES CLIENTE(IDCliente),
ALTER TABLE ENDERECOCLIENTE ADD FOREIGN KEY (EndereçoID) REFERENCES ENDERECO(EndereçoID)

ALTER TABLE ENDERECOVENDEDOR ADD FOREIGN KEY (IDVend) REFERENCES VENDEDOR(IDVend),
ALTER TABLE ENDERECOVENDEDOR ADD FOREIGN KEY (EndereçoID) REFERENCES ENDERECO(EndereçoID)

ALTER TABLE ENDERECOFORNEC ADD FOREIGN KEY (IDForn) REFERENCES FORNECEDOR(IDForn),
ALTER TABLE ENDERECOFORNEC ADD FOREIGN KEY (EndereçoID) REFERENCES ENDERECO(EndereçoID)

ALTER TABLE FORNECEDOR_CELFORN ADD FOREIGN KEY (IDForn) REFERENCES FORNECEDOR(IDForn)

ALTER TABLE CLIENTE_CELCLIENTE ADD FOREIGN KEY (IDCliente) REFERENCES CLIENTE(IDCliente)