CREATE TABLE CATEGORIA
(
  IDCat INT NOT NULL,
  NomeCat VARCHAR(20) NOT NULL,
  IDCatPai INT NULL,
  PRIMARY KEY (IDCat)
);

CREATE TABLE UNIDADEMEDIDA
(
  IDUnidade INT NOT NULL,
  NomeUnidade VARCHAR(20) NOT NULL,
  SiglaUnidade VARCHAR(5) NOT NULL,
  PRIMARY KEY (IDUnidade)
);

CREATE TABLE PRODUTO
(
  IDProd INT NOT NULL,
  NomeProd VARCHAR(20) NOT NULL,
  DescricaoProd VARCHAR(100) NULL,
  PrecoVendaProd NUMERIC(10,2) NOT NULL,
  EstoqueAtualProd NUMERIC(10,3) NOT NULL,
  PrecoCustoProd NUMERIC(10,2) NOT NULL,
  IDUnidade INT NOT NULL,
  IDCat INT NOT NULL,
  PRIMARY KEY (IDProd),

  CHECK (PrecoVendaProd >= 0),
  CHECK (EstoqueAtualProd >= 0),
  CHECK (PrecoCustoProd >= 0)
);

CREATE TABLE FORNECEDOR
(
  IDForn INT NOT NULL,
  NomeForn VARCHAR(50) NOT NULL,
  CNPJForn CHAR(14) NOT NULL UNIQUE,
  PRIMARY KEY (IDForn)
);

CREATE TABLE CLIENTE
(
  IDCliente INT NOT NULL,
  NomeCliente VARCHAR(50) NOT NULL,
  DataNascCliente DATE NOT NULL,
  CPFCliente CHAR(11) NOT NULL UNIQUE,
  PRIMARY KEY (IDCliente)
);

CREATE TABLE VENDEDOR
(
  IDVend INT NOT NULL,
  NomeVend VARCHAR(50) NOT NULL,
  CPFVend CHAR(11) NOT NULL UNIQUE,
  DataNascVend DATE NOT NULL,
  CelVend VARCHAR(15) NOT NULL,
  SalarioVend NUMERIC(10,2) NOT NULL,
  PRIMARY KEY (IDVend),

  CHECK (SalarioVend >= 0)
);

CREATE TABLE CAIXA
(
  IDCaixa INT NOT NULL,
  TipoCaixa VARCHAR(20) NOT NULL,
  PRIMARY KEY (IDCaixa)
);

CREATE TABLE OPERACAOCAIXA
(
  IDOperacao INT NOT NULL,
  DataOpAber TIMESTAMP NOT NULL,
  ValorOpAber NUMERIC(10,2) NOT NULL,
  DataOpFecham TIMESTAMP NOT NULL,
  ValorOpFecham NUMERIC(10,2) NOT NULL,
  SaldoOp NUMERIC(10,2) NOT NULL,
  IDVend INT NOT NULL,
  IDCaixa INT NOT NULL,
  PRIMARY KEY (IDOperacao),

  CHECK (ValorOpAber >= 0),
  CHECK (ValorOpFecham >= 0)
);

CREATE TABLE PEDIDO
(
  IDPedido INT NOT NULL,
  ValorTotalPedido NUMERIC(10,2) NOT NULL,
  DataPedido TIMESTAMP NOT NULL,
  TipoPedido VARCHAR(20) NOT NULL,
  IDCliente INT NOT NULL,
  IDOperacao INT NOT NULL,
  PRIMARY KEY (IDPedido),

  CHECK (ValorTotalPedido >= 0)
);

CREATE TABLE PAGAMENTO
(
  IDPag INT NOT NULL,
  MetodoPag VARCHAR(20) NOT NULL,
  ValorPag NUMERIC(10,2) NOT NULL,
  DataPag TIMESTAMP NOT NULL,
  IDPedido INT NOT NULL,
  PRIMARY KEY (IDPag),

  CHECK (ValorPag >= 0)
);

CREATE TABLE ITEMPEDIDO
(
  IDProd INT NOT NULL,
  IDPedido INT NOT NULL,
  QtdItem NUMERIC(10,3) NOT NULL,
  DescItem NUMERIC(10,2) DEFAULT 0,
  PrecoUn NUMERIC(10,2) NOT NULL,
  PRIMARY KEY (IDProd, IDPedido),

  CHECK (QtdItem > 0),
  CHECK (DescItem >= 0),
  CHECK (PrecoUn >= 0)
);

CREATE TABLE PERDAESTOQUE
(
  IDPerda INT NOT NULL,
  DataPerda TIMESTAMP NOT NULL,
  QtdPerda NUMERIC(10,3) NOT NULL,
  MotivoPerda VARCHAR(100) NOT NULL,
  ValorUnPerda NUMERIC(10,2) NOT NULL,
  IDProd INT NOT NULL,
  PRIMARY KEY (IDPerda),

  CHECK (QtdPerda > 0),
  CHECK (ValorUnPerda >= 0)
);

CREATE TABLE ENTRADAESTOQUE
(
  IDEntrada INT NOT NULL,
  IDForn INT NOT NULL,
  IDProd INT NOT NULL,
  EntradaData TIMESTAMP NOT NULL,
  EntradaQtd NUMERIC(10,3) NOT NULL,
  EntradaPreco NUMERIC(10,2) NOT NULL,
  PRIMARY KEY (IDEntrada),

  CHECK (EntradaQtd > 0),
  CHECK (EntradaPreco >= 0)
);

CREATE TABLE ENDERECO
(
  IDEndereco INT NOT NULL,
  RuaEnd VARCHAR(35) NOT NULL,
  NumeroEnd INT NOT NULL,
  ComplemEnd VARCHAR(20),
  CEPEnd CHAR(8) NOT NULL,
  BairroEnd VARCHAR(20) NOT NULL,
  CidadeEnd VARCHAR(25) NOT NULL,
  EstadoEnd CHAR(2) NOT NULL,
  PaisEnd VARCHAR(20) NOT NULL,
  PRIMARY KEY (IDEndereco)
);

CREATE TABLE ENDERECOCLIENTE
(
  IDCliente INT NOT NULL,
  IDEndereco INT NOT NULL,
  PRIMARY KEY (IDCliente, IDEndereco)
);

CREATE TABLE ENDERECOVENDEDOR
(
  IDVend INT NOT NULL UNIQUE,
  IDEndereco INT NOT NULL,
  PRIMARY KEY (IDVend, IDEndereco)
);

CREATE TABLE ENDERECOFORNEC
(
  IDForn INT NOT NULL,
  IDEndereco INT NOT NULL,
  PRIMARY KEY (IDForn, IDEndereco)
);

CREATE TABLE FORNECEDOR_CELFORN
(
  CelForn VARCHAR(15) NOT NULL,
  IDForn INT NOT NULL,
  PRIMARY KEY (CelForn, IDForn)
);

CREATE TABLE CLIENTE_CELCLIENTE
(
  CelCliente VARCHAR(15) NOT NULL,
  IDCliente INT NOT NULL,
  PRIMARY KEY (CelCliente, IDCliente)
);

ALTER TABLE CATEGORIA
ADD FOREIGN KEY (IDCatPai) REFERENCES CATEGORIA(IDCat);

ALTER TABLE PRODUTO
ADD FOREIGN KEY (IDCat) REFERENCES CATEGORIA(IDCat);

ALTER TABLE OPERACAOCAIXA
ADD FOREIGN KEY (IDVend) REFERENCES VENDEDOR(IDVend);

ALTER TABLE OPERACAOCAIXA
ADD FOREIGN KEY (IDCaixa) REFERENCES CAIXA(IDCaixa);

ALTER TABLE PEDIDO
ADD FOREIGN KEY (IDCliente) REFERENCES CLIENTE(IDCliente);

ALTER TABLE PEDIDO
ADD FOREIGN KEY (IDOperacao) REFERENCES OPERACAOCAIXA(IDOperacao);

ALTER TABLE PAGAMENTO
ADD FOREIGN KEY (IDPedido) REFERENCES PEDIDO(IDPedido);

ALTER TABLE ITEMPEDIDO
ADD FOREIGN KEY (IDProd) REFERENCES PRODUTO(IDProd);

ALTER TABLE ITEMPEDIDO
ADD FOREIGN KEY (IDPedido) REFERENCES PEDIDO(IDPedido);

ALTER TABLE PERDAESTOQUE
ADD FOREIGN KEY (IDProd) REFERENCES PRODUTO(IDProd);

ALTER TABLE ENTRADAESTOQUE
ADD FOREIGN KEY (IDForn) REFERENCES FORNECEDOR(IDForn);

ALTER TABLE ENTRADAESTOQUE
ADD FOREIGN KEY (IDProd) REFERENCES PRODUTO(IDProd);

ALTER TABLE ENDERECOCLIENTE
ADD FOREIGN KEY (IDCliente) REFERENCES CLIENTE(IDCliente);

ALTER TABLE ENDERECOCLIENTE
ADD FOREIGN KEY (IDEndereco) REFERENCES ENDERECO(IDEndereco);

ALTER TABLE ENDERECOVENDEDOR
ADD FOREIGN KEY (IDVend) REFERENCES VENDEDOR(IDVend);

ALTER TABLE ENDERECOVENDEDOR
ADD FOREIGN KEY (IDEndereco) REFERENCES ENDERECO(IDEndereco);

ALTER TABLE ENDERECOFORNEC
ADD FOREIGN KEY (IDForn) REFERENCES FORNECEDOR(IDForn);

ALTER TABLE ENDERECOFORNEC
ADD FOREIGN KEY (IDEndereco) REFERENCES ENDERECO(IDEndereco);

ALTER TABLE FORNECEDOR_CELFORN
ADD FOREIGN KEY (IDForn) REFERENCES FORNECEDOR(IDForn);

ALTER TABLE CLIENTE_CELCLIENTE
ADD FOREIGN KEY (IDCliente) REFERENCES CLIENTE(IDCliente);

ALTER TABLE PRODUTO
ADD FOREIGN KEY (IDUnidade) REFERENCES UNIDADEMEDIDA(IDUnidade);
